databases:
  - name: BookMarks_DB
    databaseName: bookmarks_db_vs3y
    user: BookMarks_DB
    region: singapore

services:
  - type: web
    name: BookMarks
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BookMarks_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
